### ISSUE TITLE
Upgrade rust-protobuf v3 from v2 

### ISSUE THREAD

**Issue by utam0k** [checkpoint-restore/rust-criu#11]
Unfortunately, now it seems failed.
https://github.com/checkpoint-restore/rust-criu/pull/9

**Comment by adrianreber** [comment]
Is this still necessary? Upgrade to 3.x?

**Comment by utam0k** [comment]
@adrianreber now, it works fine. But do we need to upgrade the future, right?

**Comment by adrianreber** [comment]
See #15
