### ISSUE TITLE
docs.rs Failing to build

### ISSUE THREAD

**Issue by cpuguy83** [checkpoint-restore/rust-criu#14]
See build logs: https://docs.rs/crate/rust-criu/0.2.0/builds/579956

I believe this is because build.rs is unconditionally generating protobufs and the output is being written to a read-only path.
If that is the problem, would it make sense to have a separate create feature for generating protos?

**Comment by adrianreber** [comment]
Thanks. We will look into it. There is even a PR open for that (#13) from someone wanting the same.

I guess our background is too strong in C where we always generated protobuf during compile and never checked it in. But we have already seen it in the Go bindings that pre-generating is expected.

**Comment by adrianreber** [comment]
Should be fixed now with version 0.4.0. Thanks for letting us know.

**Comment by utam0k** [comment]
@adrianreber Thanks a lot :bow: :heart_eyes:
