### ISSUE TITLE
[BUG] Dependency `protobuf` not correctly specified

### ISSUE THREAD

**Issue by madonuko** [checkpoint-restore/rust-criu#19]
# Your crate is BROKEN

Your crate `rust-criu` does not have the correct dependency requirement for `protobuf`:
[`Cargo.toml:13`](https://github.com/checkpoint-restore/rust-criu/blob/3a228e8c474fe781eafd50ff13b80c8710e68b94/Cargo.toml#L13):
```toml
protobuf = "3.2.0"
```

This is fatal as this WILL [bring build errors](https://github.com/terrapkg/packages/actions/runs/6691482351/job/18178806142#step:7:3271) on anything that depends on your crate once a newer version of `protobuf` is available.

### Solution

Specify the version for `protobuf` [exactly](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#comparison-requirements):
```toml
protobuf = "= 3.2.0"
```
and consider yanking previous versions of this crate. (All of them break anyway.)

And plus, now you can safely remove `rust_criu_protobuf/rpc.rs:26` knowing that the `protobuf` version is definitely `3.2.0`.

**Comment by MalteJ** [comment]
may I ask you to release this change as a new crate version - maybe 0.4.1, so we can vendor it?

Thanks!
