### ISSUE TITLE
Publish crates.io

### ISSUE THREAD

**Issue by utam0k** [checkpoint-restore/rust-criu#2]
What do you think?

**Comment by adrianreber** [comment]
Are there any advantages to it. I have nothing against it, but if I do not have to create another account and if it works for youki I would like to defer it. If you think it would be better we can easily do it.

@rst0git what do you think? I do not really have an opinion.

**Comment by utam0k** [comment]
As you know youki depends on this project. So, if this project does not register with crates.io, youki cannot register with crates.io. If it is not too difficult, I would appreciate it.

**Comment by rst0git** [comment]
Make sense. I also think it might be a good idea.

**Comment by adrianreber** [comment]
Thanks to @MostlyAmiable this is now done. Version 0.2.0 is available from https://crates.io/crates/rust-criu
